package Vista;

import Modelo.ManejoInfo;
import Controlador.Configuraciones;

import javax.swing.JOptionPane;

/**
 * Clase en la que se ponen las configuraciones
 * @author Esteban Cortes
 */
public class Configurar extends javax.swing.JFrame {

    /**
     * Crea el frame configurar con sus caracteristicas y atributos.
     */
    public Configurar() {
        super("Configuracion");
        initComponents();
        labelHoras.setVisible(false);
        horas.setVisible(false);
        labelMin.setVisible(false);
        min.setVisible(false);
        labelSec.setVisible(false);
        sec.setVisible(false);
        botonConfirmar.setVisible(false);
        
        Configuraciones configuraciones = ManejoInfo.getConfiguracion();
        
        if (configuraciones.getDificultad()[0] == true)
        {
            botonFacil.setSelected(true);
        }
        else if (configuraciones.getDificultad()[1] == true)
        {
            botonMedio.setSelected(true);
        }
        else if (configuraciones.getDificultad()[2] == true)
        {
            botonDificil.setSelected(true);
        }
        
        if (configuraciones.getReloj()[0] == true)
        {
            botonCronometro.setSelected(true);
        }
        else if (configuraciones.getReloj()[1] == true)
        {
            botonTimer.setSelected(true);
            labelHoras.setVisible(true);
            horas.setVisible(true);
            labelMin.setVisible(true);
            min.setVisible(true);
            labelSec.setVisible(true);
            sec.setVisible(true);
            botonConfirmar.setVisible(true);
        }
        else if (configuraciones.getReloj()[2] == true)
        {
            botonNoReloj.setSelected(true);
        }
        
        if (configuraciones.getPosicionDelPanel()[0] == true)
        {
            botonIzquierda.setSelected(true);
        }
        else if (configuraciones.getPosicionDelPanel()[1] == true)
        {
            botonDerecha.setSelected(true);
        }
        
        if (configuraciones.getSonidoFinal()[0] == true)
        {
            botonSiPartida.setSelected(true);
        }
        else if (configuraciones.getSonidoFinal()[1] == true)
        {
            botonNoPartida.setSelected(true);
        }
        
        if (botonTimer.isSelected())
        {
            if (ManejoInfo.getTimer().getHoras() != -1)
            {
                String cantidadHoras = String.valueOf(ManejoInfo.getTimer().getHoras());
                horas.setText(cantidadHoras);
            }
            if (ManejoInfo.getTimer().getMinutos() != -1)
            {
                String cantidadMinutos = String.valueOf(ManejoInfo.getTimer().getMinutos());
                min.setText(cantidadMinutos);
            }
            if (ManejoInfo.getTimer().getSegundos() != -1)
            {
                String cantidadSegundos = String.valueOf(ManejoInfo.getTimer().getSegundos());
                sec.setText(cantidadSegundos);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDificultad = new javax.swing.ButtonGroup();
        grupoReloj = new javax.swing.ButtonGroup();
        grupoPanel = new javax.swing.ButtonGroup();
        grupoSonido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonFacil = new javax.swing.JRadioButton();
        botonMedio = new javax.swing.JRadioButton();
        botonDificil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCronometro = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        botonDerecha = new javax.swing.JRadioButton();
        botonIzquierda = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        botonSiPartida = new javax.swing.JRadioButton();
        botonNoPartida = new javax.swing.JRadioButton();
        botonTimer = new javax.swing.JRadioButton();
        botonNoReloj = new javax.swing.JRadioButton();
        botonAtras = new javax.swing.JToggleButton();
        min = new javax.swing.JTextField();
        labelMin = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        labelSec = new javax.swing.JLabel();
        horas = new javax.swing.JTextField();
        labelHoras = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Configuracion");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonFacil.setBackground(new java.awt.Color(51, 204, 0));
        grupoDificultad.add(botonFacil);
        botonFacil.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonFacil.setForeground(new java.awt.Color(255, 255, 255));
        botonFacil.setSelected(true);
        botonFacil.setText("Facil");
        botonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacilActionPerformed(evt);
            }
        });

        botonMedio.setBackground(new java.awt.Color(51, 204, 0));
        grupoDificultad.add(botonMedio);
        botonMedio.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonMedio.setForeground(new java.awt.Color(255, 255, 255));
        botonMedio.setText("Medio");
        botonMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedioActionPerformed(evt);
            }
        });

        botonDificil.setBackground(new java.awt.Color(51, 204, 0));
        grupoDificultad.add(botonDificil);
        botonDificil.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonDificil.setForeground(new java.awt.Color(255, 255, 255));
        botonDificil.setText("Dificil");
        botonDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDificilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dificultad");

        jLabel3.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reloj");

        botonCronometro.setBackground(new java.awt.Color(51, 204, 0));
        grupoReloj.add(botonCronometro);
        botonCronometro.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonCronometro.setForeground(new java.awt.Color(255, 255, 255));
        botonCronometro.setSelected(true);
        botonCronometro.setText("Cronómetro");
        botonCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCronometroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Posición del panel");

        botonDerecha.setBackground(new java.awt.Color(51, 204, 0));
        grupoPanel.add(botonDerecha);
        botonDerecha.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonDerecha.setForeground(new java.awt.Color(255, 255, 255));
        botonDerecha.setText("Derecha");
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonIzquierda.setBackground(new java.awt.Color(51, 204, 0));
        grupoPanel.add(botonIzquierda);
        botonIzquierda.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        botonIzquierda.setSelected(true);
        botonIzquierda.setText("Izquierda");
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sonido cuando se gane la partida");

        botonSiPartida.setBackground(new java.awt.Color(51, 204, 0));
        grupoSonido.add(botonSiPartida);
        botonSiPartida.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonSiPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonSiPartida.setSelected(true);
        botonSiPartida.setText("Si");
        botonSiPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiPartidaActionPerformed(evt);
            }
        });

        botonNoPartida.setBackground(new java.awt.Color(51, 204, 0));
        grupoSonido.add(botonNoPartida);
        botonNoPartida.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonNoPartida.setForeground(new java.awt.Color(255, 255, 255));
        botonNoPartida.setText("No");
        botonNoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoPartidaActionPerformed(evt);
            }
        });

        botonTimer.setBackground(new java.awt.Color(51, 204, 0));
        grupoReloj.add(botonTimer);
        botonTimer.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonTimer.setForeground(new java.awt.Color(255, 255, 255));
        botonTimer.setText("Timer");
        botonTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTimerActionPerformed(evt);
            }
        });

        botonNoReloj.setBackground(new java.awt.Color(51, 204, 0));
        grupoReloj.add(botonNoReloj);
        botonNoReloj.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonNoReloj.setForeground(new java.awt.Color(255, 255, 255));
        botonNoReloj.setText("No");
        botonNoReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoRelojActionPerformed(evt);
            }
        });

        botonAtras.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });

        labelMin.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        labelMin.setForeground(new java.awt.Color(255, 255, 255));
        labelMin.setText("minutos");

        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });

        labelSec.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        labelSec.setForeground(new java.awt.Color(255, 255, 255));
        labelSec.setText("segundos");

        horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasActionPerformed(evt);
            }
        });

        labelHoras.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        labelHoras.setForeground(new java.awt.Color(255, 255, 255));
        labelHoras.setText("horas");

        botonConfirmar.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 12)); // NOI18N
        botonConfirmar.setText("Confirmar");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNoPartida)
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(botonFacil)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCronometro)
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(botonTimer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonSiPartida)
                                    .addComponent(botonAtras)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(botonIzquierda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonMedio)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDerecha)
                    .addComponent(botonNoReloj)
                    .addComponent(botonDificil))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(62, 62, 62))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(116, 116, 116)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonConfirmar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelHoras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(labelMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(labelSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFacil)
                    .addComponent(botonDificil)
                    .addComponent(botonMedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCronometro)
                    .addComponent(botonTimer)
                    .addComponent(botonNoReloj))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoras)
                    .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMin)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSec)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIzquierda)
                    .addComponent(botonDerecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiPartida)
                    .addComponent(botonNoPartida))
                .addGap(18, 18, 18)
                .addComponent(botonAtras)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacilActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarDificultadConfiguracion(0);
    }//GEN-LAST:event_botonFacilActionPerformed

    private void botonMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedioActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarDificultadConfiguracion(1);
    }//GEN-LAST:event_botonMedioActionPerformed

    private void botonDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDificilActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarDificultadConfiguracion(2);
    }//GEN-LAST:event_botonDificilActionPerformed

    private void botonCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCronometroActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarRelojConfiguracion(0);
        labelHoras.setVisible(false);
        horas.setVisible(false);
        labelMin.setVisible(false);
        min.setVisible(false);
        labelSec.setVisible(false);
        sec.setVisible(false);
        botonConfirmar.setVisible(false);
        
        ManejoInfo.quitarHorasTimer();
        ManejoInfo.quitarMinutosTimer();
        ManejoInfo.quitarSegundosTimer();
        
        
    }//GEN-LAST:event_botonCronometroActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarPosicionDePanelConfiguracion(1);
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarPosicionDePanelConfiguracion(0);
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonSiPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiPartidaActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarSonidoFinalConfiguracion(0);
    }//GEN-LAST:event_botonSiPartidaActionPerformed

    private void botonNoPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoPartidaActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarSonidoFinalConfiguracion(1);
    }//GEN-LAST:event_botonNoPartidaActionPerformed

    private void botonTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTimerActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarRelojConfiguracion(1);
        labelHoras.setVisible(true);
        horas.setVisible(true);
        labelMin.setVisible(true);
        min.setVisible(true);
        labelSec.setVisible(true);
        sec.setVisible(true);
        botonConfirmar.setVisible(true);
    }//GEN-LAST:event_botonTimerActionPerformed

    private void botonNoRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoRelojActionPerformed
        // TODO add your handling code here:
        
        ManejoInfo.agregarRelojConfiguracion(2);
        labelHoras.setVisible(false);
        horas.setVisible(false);
        labelMin.setVisible(false);
        min.setVisible(false);
        labelSec.setVisible(false);
        sec.setVisible(false);
        botonConfirmar.setVisible(false);
        
        ManejoInfo.quitarHorasTimer();
        ManejoInfo.quitarMinutosTimer();
        ManejoInfo.quitarSegundosTimer();
    }//GEN-LAST:event_botonNoRelojActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        
        if (botonTimer.isSelected())
        {
            if (ManejoInfo.getTimer().getHoras() != -1 && ManejoInfo.getTimer().getMinutos() != -1 && ManejoInfo.getTimer().getSegundos() != -1)
            {
                Menu menu = new Menu();
                menu.setVisible(true);
                menu.setLocationRelativeTo(null);
                this.setVisible(false);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No es posible salir del panel "
                        + "ya que se deben validar los datos del timer.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            Menu menu = new Menu();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        
        String inputHoras = horas.getText();
        String inputMinutos = min.getText();
        String inputSegundos = sec.getText();
        
        boolean sonNumeros = true;
        int numHoras = -1;
        boolean banderaHoras = false;
        int numMinutos = -1;
        boolean banderaMinutos = false;
        int numSegundos = -1;
        boolean banderaSegundos = false;
        
        try 
        {
            numHoras = Integer.parseInt(inputHoras);
            numMinutos = Integer.parseInt(inputMinutos);
            numSegundos = Integer.parseInt(inputSegundos);
        }
        catch (NumberFormatException e)
        {
            sonNumeros = false;
        }
        
        if (sonNumeros = true)
        {
            if (0 <= numHoras && numHoras <= 5)
            {
                banderaHoras = true;
            }
            if (0 <= numMinutos && numMinutos <= 60)
            {
                banderaMinutos = true;
            }
            if (0 <= numSegundos && numSegundos <= 60)
            {
                banderaSegundos = true;
            }
        }
        
        if (banderaHoras && banderaMinutos && banderaSegundos)
        {
            ManejoInfo.agregarHorasTimer(numHoras);
            ManejoInfo.agregarMinutosTimer(numMinutos);
            ManejoInfo.agregarSegundosTimer(numSegundos);
            JOptionPane.showMessageDialog(this, "El timer se configuro correctamente", "Timer", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Los valores introducidos no son validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAtras;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JRadioButton botonCronometro;
    private javax.swing.JRadioButton botonDerecha;
    private javax.swing.JRadioButton botonDificil;
    private javax.swing.JRadioButton botonFacil;
    private javax.swing.JRadioButton botonIzquierda;
    private javax.swing.JRadioButton botonMedio;
    private javax.swing.JRadioButton botonNoPartida;
    private javax.swing.JRadioButton botonNoReloj;
    private javax.swing.JRadioButton botonSiPartida;
    private javax.swing.JRadioButton botonTimer;
    private javax.swing.ButtonGroup grupoDificultad;
    private javax.swing.ButtonGroup grupoPanel;
    private javax.swing.ButtonGroup grupoReloj;
    private javax.swing.ButtonGroup grupoSonido;
    private javax.swing.JTextField horas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelSec;
    private javax.swing.JTextField min;
    private javax.swing.JTextField sec;
    // End of variables declaration//GEN-END:variables
}
